name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev

    - name: Clone Kernel source
      run: |
        git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
        cd linux
        git checkout v5.14

 

    - name: Package Kernel
      run: |
        cd linux
        tar -czvf ../mrkernel.tar.gz .

    - name: Upload Kernel
      uses: actions/upload-artifact@v2
      with:
        name: mrkernel
        path: mrkernel.tar.gz
