name: Upstream to Kernel 5.4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget xz-utils

    - name: Download Kernel 5.4
      run: |
        wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.tar.xz
        tar -xf linux-5.4.tar.xz

    - name: Merge current repo changes into Kernel 5.4
      run: |
        rsync -av --progress --exclude=.git --exclude=.github --exclude=linux-5.4 . linux-5.4/
        cd linux-5.4
        git init
        git add .
        git commit -m "Initial commit for Kernel 5.4"
        git remote add origin ../.git
        git fetch origin main
        git merge origin/main --strategy-option theirs --allow-unrelated-histories --no-edit

    - name: Zip the updated kernel
      run: |
        cd linux-5.4
        zip -r ../updated_kernel_5.4.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: updated-kernel-5.4
        path: updated_kernel_5.4.zip
