name: Upstream to Kernel 5.4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev

    - name: Download Kernel 5.4
      run: |
        wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.tar.xz
        tar -xf linux-5.4.tar.xz

    - name: Prepare for merging
      run: |
        cd linux-5.4
        make mrproper

    - name: Merge current repo changes into Kernel 5.4
      run: |
        rsync -av --progress --exclude=.git --exclude=.github ../ linux-5.4/
        cd linux-5.4
        git init
        git add .
        git commit -m "Merging current repo changes into Kernel 5.4"

    - name: Zip the updated kernel
      run: |
        cd linux-5.4
        zip -r ../updated_kernel_5.4.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: updated-kernel-5.4
        path: updated_kernel_5.4.zip
